
    # Load relevant libraries
    
    require(data.table)
    
    # Extract test and training txt files of interest
    
    testfile <- read.table('UCI HAR Dataset/test/X_test.txt', header = F)
    trainfile <- read.table('UCI HAR Dataset/train/X_train.txt', header = F)
    testlabels <- read.table('UCI HAR Dataset/test/y_test.txt', header = F)
    trainlabels <- read.table('UCI HAR Dataset/train/y_train.txt', header = F)
    activitylabels <- read.table('UCI HAR Dataset/activity_labels.txt', header = F)
    subjecttest <- read.table('UCI HAR Dataset/test/subject_test.txt', header = F)
    subjecttrain <- read.table('UCI HAR Dataset/train/subject_train.txt', header = F)
    features <- read.table('UCI HAR Dataset/features.txt', header = F)
    
    # Identify Subject ID and Activity in Column Labels
    
    colnames(subjecttest) = c('Subject ID')
    colnames(subjecttrain) = c('Subject ID')
    colnames(testlabels) = c('Activity')
    colnames(trainlabels) = c('Activity')
    
    # Identify activity performed via Activity Labels
    
    testlabels$Activity <- activitylabels$V2[testlabels$Activity]
    trainlabels$Activity <- activitylabels$V2[trainlabels$Activity]
    
    # Identify feature performed via Feature Labels
    
    colnames(testfile) = features$V2
    colnames(trainfile) = features$V2
    
    # Merge test and training files
    
    test_df <- cbind(cbind(subjecttest, testfile),testlabels)
    train_df <- cbind(cbind(subjecttrain, trainfile),trainlabels)
    
    projectdata <- rbind(test_df, train_df)
    
    # Downselect 'mean' and 'stdev' columns (and keep 'Subject ID' and 'Activity' columns)
    
    filter1 <- grep(".mean.*|.std.*|Subject ID|Activity", colnames(projectdata))
    projectdata_filtered <- projectdata[filter1]   
    
    # Create the final dataset
    
    final_data <- aggregate(projectdata_filtered, list(projectdata_filtered$Activity,projectdata_filtered$`Subject ID`), mean)
    
    # Remove the columns the data was aggregated around (Subject ID and Activity)
    
    final_data$`Subject ID` = NULL
    final_data$Activity = NULL
    
    # Rename new Subject ID and Activity columns generated by the aggregate function
    
    setnames(final_data, old = c('Group.1','Group.2'), new = c('Activity','Subject ID'))
    
    # Save the end product as a txt file
    
    write.table(final_data, file = 'run_analysis.txt', row.names = FALSE)
    
